###
GET https://6z07jz4nc0.execute-api.us-east-1.amazonaws.com/ HTTP/1.1

###
POST https://7f3znsg8l1.execute-api.us-east-1.amazonaws.com/items HTTP/1.1
Content-Type: application/json

{
    "item": "IMouse"
}